name: Release

on:
  push:
    tags:
      - 'v*'

jobs:

  release-linux:
    name: Build the Linux release artifact
    runs-on: ubuntu-latest

    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.14.x

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Test
        run: go test ./...

      - name: Vet
        run: go vet ./...

      - name: Build Debian package
        uses: dawidd6/action-debian-package@v1
        with:
          source_directory: .
          artifacts_directory: dist

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: dist/*.deb
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  release-rpi:
    name: Build the Raspberry Pi release artifact
    runs-on: [ self-hosted, linux, ARM ]

    steps:
      # Trust that the runner has a good golang version
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Test
        run: go test ./...

      - name: Vet
        run: go vet ./...

      - name: Build Debian package
        uses: dawidd6/action-debian-package@v1.2.0
        with:
          source_directory: .
          artifacts_directory: dist

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: dist/*.deb
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  release-macos:
    name: Build the MacOS release artifact
    runs-on: macos-latest

    steps:
      - name: Install WhiteBox Packages
        run: |
          curl "http://s.sudre.free.fr/Software/files/Packages.dmg" --output ${HOME}/Packages.dmg
          sudo hdiutil attach ${HOME}/Packages.dmg
          find /Volumes -name "Install Packages.pkg" | xargs -I {} sudo installer -pkg "{}" -target /

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Test
        run: go test ./...

      - name: Vet
        run: go vet ./...

      - name: Build Mac package
        run: make mac-package

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: kel-agent_mac.pkg
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  release-windows:
    name: Build the Windows release artifact
    runs-on: windows-latest

    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.14.x

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Test
        run: go test ./...

      - name: Vet
        run: go vet ./...

      - name: Build
        run: make kel-agent

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: kel-agent.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
