name: Release

on:
  push:
    tags:
      - 'v*'

jobs:

  release-linux:
    name: Build the Linux release artifact
    runs-on: ubuntu-latest

    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.14.x

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Test
        run: go test ./...

      - name: Vet
        run: go vet ./...

      - name: Build Debian package
        uses: dawidd6/action-debian-package@v1
        with:
          source_directory: .
          artifacts_directory: dist

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: dist/*.deb
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  release-windows:
    name: Build the Windows release artifact
    runs-on: windows-latest

    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.14.x

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Test
        run: go test ./...

      - name: Vet
        run: go vet ./...

      - name: Build
        run: go build

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: kel-agent.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
